INSERT INTO rohlik.products (name, stock_amount, price) VALUES
                                                                    ('Organic Apples', 150, 2.99),
                                                                    ('Whole Milk 1L', 200, 1.49),
                                                                    ('White Bread', 85, 1.99),
                                                                    ('Free Range Eggs (12pk)', 120, 3.49),
                                                                    ('Cheddar Cheese 250g', 75, 3.29),
                                                                    ('Chicken Breast 500g', 60, 6.99),
                                                                    ('Atlantic Salmon Fillet 300g', 40, 9.99),
                                                                    ('Organic Bananas', 180, 1.99),
                                                                    ('Red Tomatoes', 110, 2.49),
                                                                    ( 'Potato Bag 2kg', 90, 3.99),
                                                                    ( 'Olive Oil 750ml', 65, 7.99),
                                                                    ( 'Pasta 500g', 200, 1.29),
                                                                    ( 'Rice 1kg', 150, 2.49),
                                                                    ( 'Greek Yogurt 500g', 70, 2.99),
                                                                    ( 'Orange Juice 1L', 85, 2.79),
                                                                    ( 'Dark Chocolate Bar 100g', 120, 2.49),
                                                                    ( 'Ground Coffee 250g', 60, 5.99),
                                                                    ( 'Black Tea 50 Bags', 95, 3.19),
                                                                    ( 'Sparkling Water 6pk', 110, 4.29),
                                                                    ( 'Fresh Spinach 200g', 65, 1.89);

-- Insert orders with different statuses
INSERT INTO rohlik.orders (order_status, paid_at) VALUES
                                                                         ('PAID', '2025-04-01 14:30:00'),
                                                                         ('PENDING', NULL),
                                                                         ('CANCELED', NULL),
                                                                         ('PAID', '2025-04-02 09:15:00'),
                                                                         ('EXPIRED', NULL),
                                                                         ('PENDING', NULL),
                                                                         ('PAID', '2025-04-03 16:45:00'),
                                                                         ('PAID', '2025-04-02 11:20:00'),
                                                                         ('CANCELED', NULL),
                                                                         ( 'PENDING', NULL);

-- Insert order items linking products to orders
INSERT INTO rohlik.order_items (order_id, product_id, quantity) VALUES
( 1, 5, 2),
( 1, 12, 3),
( 1, 16, 1),
( 2, 1, 5),
( 2, 8, 4),
(3, 6, 2),
(4, 3, 1),
(4, 4, 2),
(4, 14, 1),
( 4, 17, 1),
( 5, 19, 3),
( 5, 11, 1),
( 6, 2, 2),
( 6, 7, 1),
( 6, 10, 1),
( 6, 15, 2),
( 6, 18, 1),
( 7, 9, 4),
( 7, 13, 1),
( 7, 20, 2),
( 8, 5, 1),
( 8, 16, 3),
( 9, 3, 4),
( 10, 1, 3),
( 10, 6, 2),
( 10, 12, 2),
( 10, 17, 1);